language: node_js
node_js: 
  - 6
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master
branches:
  only:
  - master