language: node_js
node_js:
- 8
script: npm run build
deploy:
  provider: pages
  #skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: site
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
    secure: hrs99P0+p5A+2HvHOtKantlNKxCaw0rUd9/Xv+sr70+dv1dtntCjcmY97wlLuUtwkzNU984EZS5DFrbXbHYFgQHI6XYLjUfDO6XaPzJzx+7EbvDXPELym6rMk5/m+LGiMWqyqJSMpXGLRWVZM8X6W5Y+gFYas3Ots8MVNeEfv8XeJa9Iztg3roRwfxsdHuWNF2Ds4HCSP2PJEby8m+vTT1e0IjKk3BsJMpD7zWYlckG0dCGqPXGPdGYKoKa3oUGNTWOwz12mO7swneiIu1hsMidscRJz76SmmVOlRuojxlP2o1WweAaFdJqsoOq0a6wszTMkZHtSu7ZV895IYO0HDAGMTzw01NHWDaFxWDOO7VcRkgl9Bl1vTfET+U1Y8Anxec0LKr4FSF8003tDpS5cYzkVBmK7+/FHDCUdAQBIadtoheOfxWY3XYxK37qYBl2XfPDJQZXpOJgU/RHfdfQZaCen5dPBvM0k3XBvNreu+5b+15/LatiaeQckEq901d1SwPvWopYElduI/LOw+yDHTxfZ5tyM05Kc+cXN6QHBjWNJVKmTC23bCKvf24ut43jCAQNpOvXFY7yfiio8zVVrwtYVnSJrlz7qnKFX40ojweHd1ojoN0STUmtwgSEq/gy5lX9kShpA/1kLruruFCqKp4COmQUneeBN1hPF7+t7PJk=
